# https://taskfile.dev

version: '3'

tasks:
  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - echo "tests are not implemented!"
  
  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds: 
      - ./out.exe

  build:
    dir: '{{.USER_WORKING_DIR}}'
    sources: ["**/*.cpp", "**/*.go"]
    cmds:
      - g++ -Wall -o out.exe main.cpp
